import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {DOMParser} from 'linkedom';
import JSZip from 'jszip';
globalThis.DOMParser=DOMParser;
const {parseMusicXMLScore}=await import('../src/lib/musicxml-parser.js');
const {parseMusicXMLDocument,readMusicXMLFile,normalizeMusicXMLText}=await import('../src/lib/musicxml-import.js');
const {walkPlaybackGraph}=await import('../src/lib/score-engine-v2.js');
const xml=await readFile(new URL('../examples/synthetic-satb.musicxml',import.meta.url),'utf8');
const attrs='<attributes><divisions>1</divisions><time><beats>4</beats><beat-type>4</beat-type></time></attributes>';
const note=(duration=4,voice=1)=>`<note><pitch><step>C</step><octave>4</octave></pitch><duration>${duration}</duration><voice>${voice}</voice><type>${duration===4?'whole':duration===1?'quarter':'half'}</type></note>`;
const wrap=measures=>`<score-partwise version="4.0"><part-list><score-part id="P1"><part-name>Soprano</part-name></score-part></part-list><part id="P1">${measures}</part></score-partwise>`;
test('original synthetic SATB fixture yields four parts and ready structure',()=>{const s=parseMusicXMLScore(xml);assert.equal(s.parts.length,4);assert.equal(s.schemaVersion,4);assert.equal(s.validation.state,'ready');assert.equal(s.validation.recognitionConfidence,null);assert.deepEqual(s.parts.map(p=>p.name),['Soprano','Contralto','Tenor','Baixo']);});
test('pitch and onset have independent known reference',()=>{const s=parseMusicXMLScore(xml),notes=s.parts.flatMap(p=>p.measures.flatMap(m=>m.voices.flatMap(v=>v.events.filter(n=>!n.rest))));assert.deepEqual(notes.map(n=>n.midi),[72,67,60,48]);assert.ok(notes.every(n=>n.startBeat===0&&n.durationBeats===4));});
test('backup creates simultaneous voices without doubling measure duration',()=>{const s=parseMusicXMLScore(wrap('<measure number="1">'+attrs+note()+'<backup><duration>4</duration></backup>'+note(4,2)+'</measure>'));assert.deepEqual(s.parts[0].measures[0].voices.map(v=>v.events[0].startBeat),[0,0]);assert.equal(s.validation.state,'ready');});
test('unexplained short measures require review',()=>{const s=parseMusicXMLScore(wrap('<measure number="1">'+attrs+note(2)+'</measure>'));assert.equal(s.validation.state,'needs_review');assert.ok(s.validation.issues.some(i=>i.code==='measure_duration'));});
test('explicit pickup and complementary last measure are accepted',()=>{const last=note(3).replace('</type>','</type><dot/>');const s=parseMusicXMLScore(wrap('<measure number="0" implicit="yes">'+attrs+note(1)+'</measure><measure number="1">'+last+'</measure>'));assert.equal(s.validation.state,'ready');});
test('bounded playback graph expands a repeat consistently',()=>{const s=parseMusicXMLScore(wrap('<measure number="1">'+attrs+'<barline location="left"><repeat direction="forward"/></barline>'+note()+'</measure><measure number="2">'+note()+'<barline><repeat direction="backward"/></barline></measure>'));assert.deepEqual(walkPlaybackGraph(s.playbackGraph),[0,1,0,1]);});
test('timewise input normalizes before scoring',()=>{const t='<score-timewise version="4.0"><part-list><score-part id="P1"><part-name>Soprano</part-name></score-part></part-list><measure number="1"><part id="P1">'+attrs+note()+'</part></measure></score-timewise>';assert.match(normalizeMusicXMLText(t),/score-partwise/);assert.equal(parseMusicXMLScore(t).validation.state,'ready');});
test('missing or duplicate parts are rejected instead of invented',()=>{assert.throws(()=>parseMusicXMLDocument(xml.replace('<part id="P4">','<part id="P3">')));assert.throws(()=>parseMusicXMLDocument(xml.replace(/<part id="P4">[\s\S]*?<\/part>/,'')));});
test('custom entities and internal DTDs are rejected without fetching',()=>{assert.throws(()=>parseMusicXMLDocument('<!DOCTYPE score-partwise [<!ENTITY x SYSTEM "https://example.invalid/private">]>'+xml),/entidades/);});
test('malformed XML and excessive nesting are rejected',()=>{assert.throws(()=>parseMusicXMLDocument('<score-partwise><part-list></score-partwise>'));assert.throws(()=>parseMusicXMLDocument('<a>'.repeat(130)+'</a>'.repeat(130)),/limite/);});
test('MXL inflates only the declared score',async()=>{const z=new JSZip();z.file('META-INF/container.xml','<container><rootfiles><rootfile full-path="score.musicxml" media-type="application/vnd.recordare.musicxml+xml"/></rootfiles></container>');z.file('score.musicxml',xml);const bytes=await z.generateAsync({type:'uint8array'});const result=await readMusicXMLFile(new File([bytes],'synthetic.mxl'));assert.equal(parseMusicXMLScore(result).parts.length,4);});
